### ISSUE TITLE
Getting Null reference execption errors. When clicking a some buildings after i adjusted the min/max level of "large"districts

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/AdvancedBuildingLevelControl#9] opened 2020-07-06 19:08 UTC
Error:
----

Object reference not set to an instance of an object [System.NullReferenceException]

Details:
No details
===

Output log:

[output_log.txt](https://github.com/algernon-A/AdvancedBuildingLevelControl/files/4880764/output_log.txt)

**Comment by algernon-A** [comment] 2020-07-06 23:38
When was this triggered (e.g. what did you do immediately beforehand)?

**Comment by Sipke82** [comment] 2020-07-07 04:50
I drew a big district which contains hundreds of buildings, Rico and growables. Set min level to 2, max to 3. Click trigger upgrade, click trigger downgrade.
Then clicking a former level 4 building gives the error.

**Comment by Sipke82** [comment] 2020-07-07 17:11
Hmm I did further investigation, and started a new city. There i could not reproduce the error.

So I went back to my original game, removed all districts, saved and restarted the game. sadly still errors when i click a building.. But i think its probably not related to this mod :-S 

So i guess we can close?

**Comment by algernon-A** [comment] 2020-07-07 23:31
I can't reproduce this either, but leaving this open for now - even if another mod caused the error, this mod was what threw the exception, so I want to improve this mod to better handle any unexpected situations.  There's scope for additional parameter checking in that particular method that's listed in your log, so I'll add that as a precaution against future events.

**Comment by algernon-A** [comment] 2021-11-03 22:52
Closing as no further issues after over a year.

**Closed as completed by algernon-A** 2021-11-03 22:52 UTC
