### ISSUE TITLE
RICO buildings keep getting upgraded

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/AdvancedBuildingLevelControl#4] opened 2020-07-01 17:13 UTC
When i have a RICO lvl 1 building and I set minumum and maximum level to 2, i can keep upgrading it until level 5, using the trigger upgrade button:
![image](https://user-images.githubusercontent.com/30873812/86272429-d76b1e00-bbce-11ea-8046-dfc560806a93.png)

**Comment by algernon-A** [comment] 2020-07-02 00:33
WAD, in that the building (not district) 'trigger upgrade' function by design will ignore min/max levels - this is to allow easy adjustment for individual buildings.

Still a valid issue in that this needs to be made clearer to users.  Treating as UI improvement needed.

**Comment by Sipke82** [comment] 2020-07-03 09:57
Okay, well then I guess the maximum level for this specific building should also be upgraded. (or the minimum level in case of downgrade below the minimum level)

**Comment by algernon-A** [comment] 2020-07-03 11:54
Good point - will add.

**Comment by algernon-A** [comment] 2020-07-06 12:39
Fixed by 73564b7e5bea536e5f7d4c9129643a5d0b1f136a

**Closed as completed by algernon-A** 2020-07-06 12:39 UTC
Labels: enhancement
